#!/bin/bash

source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# COPY SOURCE FILES
#=================================================
ynh_script_progression --message="Upgrading source files..." --weight=1

cp -r ../. "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# UPDATE CONFIGURATION
#=================================================
ynh_script_progression --message="Updating configuration..." --weight=1

ynh_add_config --template="env" --destination="$install_dir/.env"

#=================================================
# UPGRADE APP
#=================================================
ynh_script_progression --message="Upgrading app..." --weight=10

pushd "$install_dir"
	rm -rf node_modules package-lock.json
	ynh_exec_warn_less ynh_exec_as $app npm install --production=false
	ynh_exec_warn_less ynh_exec_as $app env YNH_APP_ARG_PATH="$path" npm run build
popd

#=================================================
# UPDATE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Updating system configurations..." --weight=1

ynh_add_nginx_config

ynh_add_systemd_config

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Upgrade of $app completed" --last